### ISSUE TITLE
Cannot log into safenetwork

### ISSUE THREAD

**Issue by davidkazlauskas** [maidsafe/safe_core#182] opened 2015-10-22 17:50 UTC
I'm running 7 vaults at a time built by 166e26f4dd48a56aa4a1483b9156ae06f64433ad commit (from same directory).

Then I'm building small project https://github.com/davidkazlauskas/SafeNetworkTestUploader which should upload small txt files after logging in.

Then, after upload file command:

./QuickUploader upl text.txt /text.txt

login gets stuck at "Loging into account with supplied credentials" message at log_in function in the core. I would hope this should work and if user doesn't exist just return an error. Everything is on ran on the local network with default cargo build process.

**Comment by ustulation** [comment] 2015-11-03 10:01
Login would require a valid account so i hope you created an account before Logging into it. We are continuously running against the mock routing right now (`cargo build/run --features use-mock-routing`) and everything seems to be working fine. Since the actual network is not ready yet (will be very soon though), i haven't tested against the actual vaults to know if any runtime API changed (in vault, routing etc) that requires some minor tweaking - that would be more useful once things are sorted in all the crates because the static API hasn't changed (so it builds fine) ..

**Comment by ustulation** [comment] 2015-11-04 14:22
I am closing this as of now as it is running fine against mock-network. Once it is integrated to actual routing, testing would be done then again and if there is an issue we will be fixing it. Until then i cannot ascertain if the issue is in this crate or others

**Closed by ustulation** 2015-11-04 14:22 UTC
